locales:
  gvp:
    name: Pará Gavião Keyboards
    description: >-
      Mobile OS keyboards for the Pará Gavião language from the Divvun group
      at UiT.
  en:
    name: Pará Gavião Keyboards
    description: >-
      Mobile OS keyboards for the Pará Gavião language from the Divvun group
      at UiT.
  nb:
    name: Pará Gavião tastatur
    description: Mobiltastatur for Pará Gavião fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
